---
- name: Just a little bit on loops
  hosts: localhost
  gather_facts: no

  vars:
          myList:
                  - "A hyphen is an entry in a list"
                  - "This would be the 2nd item on the list"
                  - "No. 3"

  tasks:
          - name: Demo my little loop
            debug:
                    msg: "The debug module allows us to display to the screen: {{ item }}"
            loop: "{{ myList }}"

          - name: Demo a 2nd tiny loop
            debug:
                    msg: "All modules can also have LOCAL var information: {{ item }}"
            loop: "{{ myOtherList }}"
            vars:
                    myOtherList:
                            - Example of local info
                            - Only available to this task
